feat: create Json to xml policy
gravitee-io/gravitee-policy-json-xml pull request #1
Opened 2021-01-29 08:03 UTC by gcusnieux

fix gravitee-io/issues#4561

2021-02-01 09:08 UTC, ytvnr requested changes
Some remarks

1. It could be cool to add a test that take a json file and assert on the output.
2. ⚠️ There are some mistakes in the README.adoc from previous commit, at some places you keep talking about `xml-json` (see Desxription and Example sections)

2021-02-01 09:30 UTC, gcusnieux commented on src/main/java/io/gravitee/policy/json2xml/transformer/CDL.java
> +public class CDL {
plugins mustn't have too many dependencies

2021-02-01 10:12 UTC, ytvnr approved these changes
LGTM

2021-02-01 10:25 UTC, merged

2022-03-04 13:19 UTC, graviteeio commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/gravitee-io/gravitee-policy-json-xml/releases/tag/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: